language: ruby
install:
  - bundle install
rvm:
 - 2.0.0
script: bundle exec rake site:deploy --quiet

env:
  global:
  - secure: ZRhTKMEcZVcujw0rBKHx/3lTRbkhF9PMJeOZmavoJBGJwHv85BZEpuFCkxAMa2P/3OrQJG+Dzi55tk/N7JgCfAkZHnAQpRdsqrnkWBoRzjT/64/U1o3TNYfrfj9stLMjs+VRMR6EcgRli1E3n12WOT7sL5bpOrVOssuTQ4K2Jgg=
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
