---
title: Adventures aren't Fairytales
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
safe: false
lsi: true
encoding: utf-8
markdown: kramdown
permalink: "/:day-:month-:year/:title"
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
highlighter: rouge
header_img: clean/pumpkin-patch.jpg
tagline: There is no Happily Ever After, it just keeps going
author:
  name: Seth Clossman
  email: clossmans2@gmail.com
  github: clossmans2
  twitter: closs_the_man
twitter_username: closs_the_man
github_username: clossmans2
facebook_username: seth.clossman
production_url: http://i.sethclossman.com
gems:
- jekyll-archives
- jekyll-sitemap
- jekyll-feed
JB:
  version: 0.3.0
  BASE_PATH: false
  ASSET_PATH: false
  archive_path: "/archive.html"
  categories_path: "/categories.html"
  tags_path: "/tags.html"
  atom_path: "/atom.xml"
  rss_path: "/rss.xml"
  comments:
    provider: disqus
    disqus:
      short_name: blufftonclossmans
    livefyre:
      site_id: 123
    intensedebate:
      account: 123abc
    facebook:
      appid: 123
      num_posts: 5
      width: 580
      colorscheme: light
  analytics:
    provider: google
    google:
      tracking_id: UA-70362622-1
    getclicky:
      site_id: 
    mixpanel:
      token: _MIXPANEL_TOKEN_
    piwik:
      baseURL: myserver.tld/piwik
      idsite: '1'
  sharing:
    provider: like
    facebook:
      appid: '1669651593319645'
      layout: button_count
      width: false
      faces: false
      share: false
