safe: false
lsi: true
timezone: America/New_York
encoding: utf-8
markdown: kramdown
permalink: /:day-:month-:year/:title # For more see: http://jekyllrb.com/docs/permalinks/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments

header_img: clean/pumpkin-patch.jpg
# Theme Config
title: "Adventures aren't Fairytales"
tagline: "There is no Happily Ever After, it just keeps going"
author:
  name: Seth Clossman
  email: clossmans2@gmail.com
  github: clossmans2
  twitter: closs_the_man

twitter_username: closs_the_man
github_username:  clossmans2
facebook_username:  seth.clossman
production_url: http://i.sethclossman.com

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed

JB:
  version: 0.3.0
  BASE_PATH: false
  ASSET_PATH: false
  archive_path: /archive.html
  categories_path: /categories.html
  tags_path: /tags.html
  atom_path: /atom.xml
  rss_path: /rss.xml

  # Settings for comments helper
  # Set 'provider' to the comment provider you want to use.
  # Set 'provider' to false to turn commenting off globally.
  #
  comments :
    provider : disqus
    disqus :
      short_name : blufftonclossmans
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light

  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
    provider : google
    google : 
        tracking_id : 'UA-70362622-1'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik

  # Settings for sharing helper. 
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Add a tweet button 		=> provider : tweet
  # Add a like button 		=> provider : like
  # Add a plus one button 	=> provider : plusone
  # Add a HN button 		=> provider : hn
  # Add them all (i.e. hn + tweet + plusone + like) => provider : all
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider: like
    facebook :
      appid: "1669651593319645"
      layout: "button_count"
      width : false
      faces : false
      share : false
#      twitter :
#        size : 40
#        via : false
#        count : 1
# Facebook:
#   appid: Needs to be a legit facebook app id
#   layout: standard | box_count | button_count | button
#   width: false | pixel_width -> must be integer
#   faces: true | false -> tells whether to show faces
#   share: true | false -> adds an additional share button
#      googleplus :
#        size : medium
#        width :
#        annotation : bubble
#      linkedin :
#        counter : right
