source: .
destination: ./_site
exclude: [ vendor, scripts ]
timezone: America/New_York
encoding: utf-8
limit_posts: 0
highlighter: pygments
relative_permalinks: true
permalink: date
paginate_path: 'page:num'
port: 4000
safe: true
